### ISSUE TITLE
Wrong escaping of string literal macro definitions

### ISSUE THREAD

**Issue by eel76** [Caphyon/clang-power-tools#201]
I am getting errors for CMake generated projects due to wrong escaping of string literal macro definitions. Please find attached a minimalistic CMake project to reproduce this behavior.

> Start Clang Compile
> 
> VERBOSE: clang-build.ps1 invocation args: 
>   aVcxprojToCompile = W:\example.build\example.vcxproj 
>   aCppToCompile = W:\example.build\main.cpp 
>   aVcxprojConfigPlatform = Debug|x64 
>   aClangCompileFlags = -Werror -Wall -fms-compatibility-version=19.10 
> -fms-compatibility -Wmicrosoft -Wno-invalid-token-paste -Wno-unknown-pragmas 
> -Wno-unused-variable -Wno-unused-value 
>   Verbose = True 
>   aUseParallelCompile = True 
>   aVisualStudioVersion = 2017 
>   aVisualStudioSku = Professional 
>   aSolutionsPath = W:\example.build\example.sln 
>   aDisableNameRegexMatching = True 
> VERBOSE: CPU logical core count: 24
> VERBOSE: LLVM location: C:\Program Files\LLVM\bin
> VERBOSE: Scanning for solution files
> VERBOSE: Solution file paths:
> VERBOSE:   W:\example.build\example.sln
> VERBOSE: Source directory: W:\example.build\
> VERBOSE: Scanning for project files
> VERBOSE: Found 3 projects
> PROJECT: W:\example.build\example.vcxproj
> VERBOSE: Importing environment variables into current scope
> VERBOSE: SET_VAR _NT_SYMBOL_PATH: 
> srv*P:\Symbols*http://msdl.microsoft.com/download/symbols
> VERBOSE: SET_VAR _NT_SYMCACHE_PATH: P:\SymCache
> VERBOSE: SET_VAR ALLUSERSPROFILE: C:\ProgramData
> VERBOSE: SET_VAR APPDATA: C:\Users\reinbach\AppData\Roaming
> VERBOSE: SET_VAR CommonProgramFiles: C:\Program Files (x86)\Common Files
> VERBOSE: SET_VAR CommonProgramFiles(x86): C:\Program Files (x86)\Common Files
> VERBOSE: SET_VAR CommonProgramW6432: C:\Program Files\Common Files
> VERBOSE: SET_VAR COMPLUS_InstallRoot: 
> VERBOSE: SET_VAR COMPLUS_Version: 
> VERBOSE: SET_VAR COMPUTERNAME: VGPC45
> VERBOSE: SET_VAR ComSpec: C:\Windows\system32\cmd.exe
> VERBOSE: SET_VAR FP_NO_HOST_CHECK: NO
> VERBOSE: SET_VAR HOMEDRIVE: C:
> VERBOSE: SET_VAR HOMEPATH: \Users\reinbach
> VERBOSE: SET_VAR INTEL_LICENSE_FILE: C:\Program Files (x86)\Common 
> Files\Intel\Licenses
> VERBOSE: SET_VAR LOCALAPPDATA: C:\Users\reinbach\AppData\Local
> VERBOSE: SET_VAR LOGONSERVER: \\DC1
> VERBOSE: SET_VAR MSBuildLoadMicrosoftTargetsReadOnly: true
> VERBOSE: SET_VAR MSMPI_BIN: C:\Program Files\Microsoft MPI\Bin\
> VERBOSE: SET_VAR NUMBER_OF_PROCESSORS: 24
> VERBOSE: SET_VAR OneDrive: P:\reinbach\OneDrive
> VERBOSE: SET_VAR OS: Windows_NT
> VERBOSE: SET_VAR Path: C:\Program Files\Microsoft 
> MPI\Bin\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Windows 
> Resource 
> Kits\Tools\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\
> System32\WindowsPowerShell\v1.0\;c:\Program Files (x86)\Microsoft SQL 
> Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL 
> Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL 
> Server\100\DTS\Binn\;C:\Program Files\Microsoft Windows Performance 
> Toolkit\;C:\Program Files (x86)\Windows Kits\8.0\Windows Performance 
> Toolkit\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files 
> (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files\Microsoft SQL 
> Server\110\Tools\Binn\;C:\Program Files (x86)\Windows Kits\8.1\Windows 
> Performance Toolkit\;C:\Program Files\Microsoft SQL 
> Server\120\Tools\Binn\;C:\Program Files (x86)\Visual Leak 
> Detector\bin\Win32;C:\Program Files (x86)\Visual Leak 
> Detector\bin\Win64;C:\Program Files\Microsoft SQL 
> Server\130\Tools\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows 
> Performance Toolkit\;C:\Program Files\TortoiseGit\bin;C:\Program 
> Files\CMake\bin;C:\HashiCorp\Vagrant\bin;C:\Windows\System32\WindowsPowerShell\
> v1.0\;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program 
> Files\TortoiseSVN\bin;C:\Program 
> Files\Git\cmd;C:\Users\reinbach\AppData\Local\Conan\conan;c:\work\bin;C:\Progra
> m Files\Microsoft MPI\Bin\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files
>  (x86)\Windows Resource 
> Kits\Tools\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\
> System32\WindowsPowerShell\v1.0\;c:\Program Files (x86)\Microsoft SQL 
> Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL 
> Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL 
> Server\100\DTS\Binn\;C:\Program Files\Microsoft Windows Performance 
> Toolkit\;C:\Program Files (x86)\Windows Kits\8.0\Windows Performance 
> Toolkit\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files 
> (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files\Microsoft SQL 
> Server\110\Tools\Binn\;C:\Program Files (x86)\Windows Kits\8.1\Windows 
> Performance Toolkit\;C:\Program Files\Microsoft SQL 
> Server\120\Tools\Binn\;C:\Program Files (x86)\Visual Leak 
> Detector\bin\Win32;C:\Program Files (x86)\Visual Leak 
> Detector\bin\Win64;C:\Program Files\Microsoft SQL 
> Server\130\Tools\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows 
> Performance Toolkit\;C:\Program Files\TortoiseGit\bin;C:\Program 
> Files\CMake\bin;C:\HashiCorp\Vagrant\bin;C:\Windows\System32\WindowsPowerShell\
> v1.0\;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program 
> Files\TortoiseSVN\bin;C:\Program 
> Files\Git\cmd;C:\Users\reinbach\AppData\Local\Gource\cmd;C:\Program 
> Files\LLVM\bin
> VERBOSE: SET_VAR PATHEXT: 
> .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL
> VERBOSE: SET_VAR PkgDefApplicationConfigFile: 
> C:\Users\reinbach\AppData\Local\Microsoft\VisualStudio\15.0_739ffdf9\devenv.exe
> .config
> VERBOSE: SET_VAR PROCESSOR_ARCHITECTURE: x86
> VERBOSE: SET_VAR PROCESSOR_ARCHITEW6432: AMD64
> VERBOSE: SET_VAR PROCESSOR_IDENTIFIER: Intel64 Family 6 Model 44 Stepping 2, 
> GenuineIntel
> VERBOSE: SET_VAR PROCESSOR_LEVEL: 6
> VERBOSE: SET_VAR PROCESSOR_REVISION: 2c02
> VERBOSE: SET_VAR ProgramData: C:\ProgramData
> VERBOSE: SET_VAR ProgramFiles: C:\Program Files (x86)
> VERBOSE: SET_VAR ProgramFiles(x86): C:\Program Files (x86)
> VERBOSE: SET_VAR ProgramW6432: C:\Program Files
> VERBOSE: SET_VAR PSExecutionPolicyPreference: Bypass
> VERBOSE: SET_VAR PSModulePath: C:\Program 
> Files\WindowsPowerShell\Modules;C:\Users\reinbach\Documents\WindowsPowerShell\M
> odules;C:\Program Files 
> (x86)\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modu
> les
> VERBOSE: SET_VAR PUBLIC: C:\Users\Public
> VERBOSE: SET_VAR SESSIONNAME: Console
> VERBOSE: SET_VAR SystemDrive: C:
> VERBOSE: SET_VAR SystemRoot: C:\Windows
> VERBOSE: SET_VAR TEMP: C:\Windows\TEMP
> VERBOSE: SET_VAR TMP: C:\Users\reinbach\AppData\Local\Temp
> VERBOSE: SET_VAR USERDNSDOMAIN: VOLUMEGRAPHICS.COM
> VERBOSE: SET_VAR USERDOMAIN: VOLUMEGRAPHICS
> VERBOSE: SET_VAR USERNAME: reinbach
> VERBOSE: SET_VAR USERPROFILE: C:\Users\reinbach
> VERBOSE: SET_VAR VBOX_MSI_INSTALL_PATH: C:\Program Files\Oracle\VirtualBox\
> VERBOSE: SET_VAR VisualStudioDir: C:\Users\reinbach\Documents\Visual Studio 
> 2017
> VERBOSE: SET_VAR VisualStudioEdition: Microsoft Visual Studio Professional 2017
> VERBOSE: SET_VAR VisualStudioVersion: 15.0
> VERBOSE: SET_VAR VS110COMNTOOLS: C:\Program Files (x86)\Microsoft Visual Studio
>  11.0\Common7\Tools\
> VERBOSE: SET_VAR VS120COMNTOOLS: C:\Program Files (x86)\Microsoft Visual Studio
>  12.0\Common7\Tools\
> VERBOSE: SET_VAR VS140COMNTOOLS: C:\Program Files (x86)\Microsoft Visual Studio
>  14.0\Common7\Tools\
> VERBOSE: SET_VAR VSAPPIDDIR: C:\Program Files (x86)\Microsoft Visual 
> Studio\2017\Professional\Common7\IDE\
> VERBOSE: SET_VAR VSAPPIDNAME: devenv.exe
> VERBOSE: SET_VAR VSLANG: 1033
> VERBOSE: SET_VAR VSSDK140Install: C:\Program Files (x86)\Microsoft Visual 
> Studio 14.0\VSSDK\
> VERBOSE: SET_VAR VSSKUEDITION: Professional
> VERBOSE: SET_VAR windir: C:\Windows
> VERBOSE: SET_VAR MSBuildProjectFullPath: W:\example.build\example.vcxproj
> VERBOSE: SET_VAR ProjectDir: W:\example.build\
> VERBOSE: SET_VAR MSBuildProjectExtension: .vcxproj
> VERBOSE: SET_VAR MSBuildProjectFile: example.vcxproj
> VERBOSE: SET_VAR MSBuildProjectName: example
> VERBOSE: SET_VAR MSBuildProjectDirectory: W:\example.build\
> VERBOSE: SET_VAR MSBuildProgramFiles32: C:\Program Files (x86)
> VERBOSE: SET_VAR ProjectName: example
> VERBOSE: SET_VAR TargetName: example
> VERBOSE: SET_VAR VisualStudioVersion: 15.0
> VERBOSE: SET_VAR MSBuildToolsVersion: 15.0
> VERBOSE: SET_VAR SolutionDir: W:\example.build\
> VERBOSE: 
> Sanitizing W:\example.build\example.vcxproj
> VERBOSE: SET_VAR MSBuildThisFileFullPath: W:\example.build\example.vcxproj
> VERBOSE: SET_VAR MSBuildThisFileExtension: .vcxproj
> VERBOSE: SET_VAR MSBuildThisFile: example.vcxproj
> VERBOSE: SET_VAR MSBuildThisFileName: example
> VERBOSE: SET_VAR MSBuildThisFileDirectory: W:\example.build\
> VERBOSE: SET_VAR Configuration: Debug
> VERBOSE: SET_VAR Platform: x64
> VERBOSE: SET_VAR ProjectGuid: {8567C08C-A6F3-3FA8-B778-0127438A64E9}
> VERBOSE: SET_VAR WindowsTargetPlatformVersion: 10.0.16299.0
> VERBOSE: SET_VAR Keyword: Win32Proj
> VERBOSE: SET_VAR Platform: x64
> VERBOSE: SET_VAR ProjectName: example
> VERBOSE: SET_VAR VCProjectUpgraderObjectName: NoUpgrade
> VERBOSE: Could not find property sheet \Microsoft.Cpp.Default.props
> VERBOSE: SET_VAR ConfigurationType: Application
> VERBOSE: SET_VAR CharacterSet: MultiByte
> VERBOSE: SET_VAR PlatformToolset: v141
> VERBOSE: Could not find property sheet \Microsoft.Cpp.props
> VERBOSE: SET_VAR _ProjectFileVersion: 10.0.20506.1
> VERBOSE: SET_VAR OutDir: W:\example.build\Debug\
> VERBOSE: SET_VAR IntDir: example.dir\Debug\
> VERBOSE: SET_VAR TargetName: example
> VERBOSE: SET_VAR TargetExt: .exe
> VERBOSE: SET_VAR LinkIncremental: true
> VERBOSE: SET_VAR GenerateManifest: true
> VERBOSE: Could not find property sheet \Microsoft.Cpp.targets
> VERBOSE: Force includes: 
> VERBOSE: PCH not enabled for this project!
> VERBOSE: Preprocessor definitions:
> VERBOSE:   -DWIN32
> VERBOSE:   -D_WINDOWS
> VERBOSE:   -DPROJECT_NAME=""""""example""""""
> VERBOSE:   -DSTRING_WITH_SPACE=""""""STRING WITH SPACE""""""
> VERBOSE:   -DCMAKE_INTDIR=""""""Debug""""""
> VERBOSE:   -D_DEBUG_FUNCTIONAL_MACHINERY
> VERBOSE: Platform toolset: v141
> VERBOSE: Additional includes:
> VERBOSE:   
> VERBOSE: Visual Studio location: C:\Program Files (x86)\Microsoft Visual 
> Studio\2017\Professional
> VERBOSE: MSCVER: 14.12.25827
> VERBOSE: WinSDK version: 10.0.16299.0
> VERBOSE: Include directories:
> VERBOSE:   W:\example.build\
> VERBOSE:   C:\Program Files (x86)\Microsoft Visual 
> Studio\2017\Professional\VC\Tools\MSVC\14.12.25827\include
> VERBOSE:   C:\Program Files (x86)\Microsoft Visual 
> Studio\2017\Professional\VC\Tools\MSVC\14.12.25827\atlmfc\include
> VERBOSE:   C:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0\ucrt
> VERBOSE:   C:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0\um
> VERBOSE:   C:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0\shared
> VERBOSE:   C:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0\winrt
> VERBOSE:   
> VERBOSE: Processing 1 cpps
> VERBOSE: SET_VAR ClangPowerTools:CppStd: c++14
> VERBOSE: Clang job tool: clang++.exe
> VERBOSE: Clang job args[0]: -x c++ "W:\example.build\main.cpp" -std=c++14 
> -Werror -Wall -fms-compatibility-version=19.10 -fms-compatibility -Wmicrosoft 
> -Wno-invalid-token-paste -Wno-unknown-pragmas -Wno-unused-variable 
> -Wno-unused-value -fsyntax-only -DWIN32 -D_WINDOWS 
> -DPROJECT_NAME=""""""example"""""" -DSTRING_WITH_SPACE=""""""STRING WITH 
> SPACE"""""" -DCMAKE_INTDIR=""""""Debug"""""" -D_DEBUG_FUNCTIONAL_MACHINERY
> 1: W:\example.build\main.cpp
> clang++.exe: error: no such file or directory: 'WITH'
> clang++.exe: error: 
> no such file or directory: 'SPACE""'
> 
> 
> Got errors.
> VERBOSE: Cleaning up PCH temporaries:
> 
> Done Clang Compile
> 

[CMakeLists.txt](https://github.com/Caphyon/clang-power-tools/files/1634669/CMakeLists.txt)

**Comment by jiixyj** [comment]
The `ns:PreprocessorDefinitions` variable seems to have all instances of `"` replaced by `""`. Maybe VS already escapes the contents for wrapping inside double quotes?

Can you try this patch? It works for me.
https://gist.github.com/jiixyj/a39b9fbafaf660235af06c563ef332d8

**Comment by eel76** [comment]
In the _vcxproj_ file no escaping of double quotes took place. However, i can confirm that `(Select-ProjectNodes $kVcxprojXpathPreprocessorDefs).InnerText` already has all instances of `"` replaced by `""`.

Your patch didn't work for me, but a slightly different one did: https://gist.github.com/eel76/84a3421fd67b49e5045130bbe43b6e53

**Comment by hero101111** [comment]
Hello,

We've pushed a fix for the double quote escaping issue. 
An updated release will be released shortly.

Regards,
Gabriel

---

Please note that this fix is currently live only for the github repository.
The latest Visual Studio extension does not contain the fix. It will be included in the next release.

Until then, as a workaround, you can manually replace `clang-build.ps1` in the VS extension directory with the latest from github. To locate the extension directory search for `clang-build.ps1` in `%LOCALAPPDATA%`

Don't forget to restart Visual Studio after replacing the script file.

**Comment by eel76** [comment]
Hello,

i cloned the github repository again. However pull request #205 didn't fix my issue:

> clang-build.ps1 invocation args: 
>   aSolutionsPath = W:\test\build 
>   aClangCompileFlags = -Werror -Wall -fms-compatibility-version=19.10 -Wmicrosoft -Wno-invalid-token-paste 
> -Wno-unknown-pragmas -Wno-unused-value 
>   aVisualStudioVersion = 2017 
>   aVisualStudioSku = Professional 
>   aTidyHeaderFilter = .* 
> 
> CPU logical core count: 24
> Scanning for solution files
> Solution file paths:
>   W:\test\build\example.sln
> Source directory: W:\test\build
> Scanning for project files
> Found 3 projects
> PROCESSING ALL PROJECTS
> 
> PROJECT #3: W:\test\build\ALL_BUILD.vcxproj
> Importing environment variables into current scope
> SET_VAR _NT_SYMBOL_PATH: srv*P:\Symbols*http://msdl.microsoft.com/download/symbols
> SET_VAR _NT_SYMCACHE_PATH: P:\SymCache
> SET_VAR ALLUSERSPROFILE: C:\ProgramData
> SET_VAR APPDATA: C:\Users\reinbach\AppData\Roaming
> SET_VAR CommonProgramFiles: C:\Program Files\Common Files
> SET_VAR CommonProgramFiles(x86): C:\Program Files (x86)\Common Files
> SET_VAR CommonProgramW6432: C:\Program Files\Common Files
> SET_VAR COMPUTERNAME: VGPC45
> SET_VAR ComSpec: C:\Windows\system32\cmd.exe
> SET_VAR FP_NO_HOST_CHECK: NO
> SET_VAR HOMEDRIVE: C:
> SET_VAR HOMEPATH: \Users\reinbach
> SET_VAR INCLUDE: W:\test\build;C:\Program Files (x86)\Microsoft Visual 
> Studio\2017\Professional\VC\Tools\MSVC\14.12.25827\include;C:\Program Files (x86)\Microsoft Visual 
> Studio\2017\Professional\VC\Tools\MSVC\14.12.25827\atlmfc\include;C:\Program Files (x86)\Windows 
> Kits\10\Include\10.0.10240.0\ucrt;C:\Program Files (x86)\Windows Kits\8.1\Include\um;C:\Program Files (x86)\Windows 
> Kits\8.1\Include\shared;C:\Program Files (x86)\Windows Kits\8.1\Include\winrt;
> SET_VAR INTEL_LICENSE_FILE: C:\Program Files (x86)\Common Files\Intel\Licenses
> SET_VAR LOCALAPPDATA: C:\Users\reinbach\AppData\Local
> SET_VAR LOGONSERVER: \\DC2
> SET_VAR MSMPI_BIN: C:\Program Files\Microsoft MPI\Bin\
> SET_VAR NUMBER_OF_PROCESSORS: 24
> SET_VAR OneDrive: P:\reinbach\OneDrive
> SET_VAR OS: Windows_NT
> SET_VAR Path: %SystemRoot%\system32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft 
> MPI\Bin\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Windows Resource Kits\Tools\;C:\Windows\system32;C:
> \Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;c:\Program Files (x86)\Microsoft SQL 
> Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL 
> Server\100\DTS\Binn\;C:\Program Files\Microsoft Windows Performance Toolkit\;C:\Program Files (x86)\Windows 
> Kits\8.0\Windows Performance Toolkit\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files 
> (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files 
> (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program 
> Files (x86)\Visual Leak Detector\bin\Win32;C:\Program Files (x86)\Visual Leak Detector\bin\Win64;C:\Program 
> Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performance 
> Toolkit\;C:\Program Files\TortoiseGit\bin;C:\HashiCorp\Vagrant\bin;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windo
> ws\System32\WindowsPowerShell\v1.0\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\Git\cmd;C:\Program 
> Files\CMake\bin;C:\Users\reinbach\AppData\Local\Conan\conan;c:\work\bin;C:\Program Files\Microsoft 
> MPI\Bin\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Windows Resource Kits\Tools\;C:\Windows\system32;C:
> \Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;c:\Program Files (x86)\Microsoft SQL 
> Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL 
> Server\100\DTS\Binn\;C:\Program Files\Microsoft Windows Performance Toolkit\;C:\Program Files (x86)\Windows 
> Kits\8.0\Windows Performance Toolkit\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files 
> (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files 
> (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program 
> Files (x86)\Visual Leak Detector\bin\Win32;C:\Program Files (x86)\Visual Leak Detector\bin\Win64;C:\Program 
> Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performance 
> Toolkit\;C:\Program Files\TortoiseGit\bin;C:\HashiCorp\Vagrant\bin;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windo
> ws\System32\WindowsPowerShell\v1.0\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\Git\cmd;C:\Program 
> Files\CMake\bin;C:\Users\reinbach\AppData\Local\Gource\cmd;C:\Program Files\LLVM\bin
> SET_VAR PATHEXT: .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL
> SET_VAR PROCESSOR_ARCHITECTURE: AMD64
> SET_VAR PROCESSOR_IDENTIFIER: Intel64 Family 6 Model 44 Stepping 2, GenuineIntel
> SET_VAR PROCESSOR_LEVEL: 6
> SET_VAR PROCESSOR_REVISION: 2c02
> SET_VAR ProgramData: C:\ProgramData
> SET_VAR ProgramFiles: C:\Program Files
> SET_VAR ProgramFiles(x86): C:\Program Files (x86)
> SET_VAR ProgramW6432: C:\Program Files
> SET_VAR PSModulePath: C:\Users\reinbach\Documents\WindowsPowerShell\Modules;C:\Program 
> Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules
> SET_VAR PUBLIC: C:\Users\Public
> SET_VAR SESSIONNAME: Console
> SET_VAR SystemDrive: C:
> SET_VAR SystemRoot: C:\Windows
> SET_VAR TEMP: C:\Windows\TEMP
> SET_VAR TMP: C:\Users\reinbach\AppData\Local\Temp
> SET_VAR USERDNSDOMAIN: VOLUMEGRAPHICS.COM
> SET_VAR USERDOMAIN: VOLUMEGRAPHICS
> SET_VAR USERNAME: reinbach
> SET_VAR USERPROFILE: C:\Users\reinbach
> SET_VAR VBOX_MSI_INSTALL_PATH: C:\Program Files\Oracle\VirtualBox\
> SET_VAR VS110COMNTOOLS: C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\Tools\
> SET_VAR VS120COMNTOOLS: C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools\
> SET_VAR VS140COMNTOOLS: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\
> SET_VAR VSSDK140Install: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VSSDK\
> SET_VAR windir: C:\Windows
> SET_VAR MSBuildProjectFullPath: W:\test\build\ALL_BUILD.vcxproj
> SET_VAR ProjectDir: W:\test\build\
> SET_VAR MSBuildProjectExtension: .vcxproj
> SET_VAR MSBuildProjectFile: ALL_BUILD.vcxproj
> SET_VAR MSBuildProjectName: ALL_BUILD
> SET_VAR MSBuildProjectDirectory: W:\test\build\
> SET_VAR MSBuildProgramFiles32: C:\Program Files (x86)
> SET_VAR ProjectName: ALL_BUILD
> SET_VAR TargetName: ALL_BUILD
> SET_VAR VisualStudioVersion: 15.0
> SET_VAR MSBuildToolsVersion: 15.0
> SET_VAR SolutionDir: W:\test\build\
> 
> Sanitizing W:\test\build\ALL_BUILD.vcxproj
> SET_VAR MSBuildThisFileFullPath: W:\test\build\ALL_BUILD.vcxproj
> SET_VAR MSBuildThisFileExtension: .vcxproj
> SET_VAR MSBuildThisFile: ALL_BUILD.vcxproj
> SET_VAR MSBuildThisFileName: ALL_BUILD
> SET_VAR MSBuildThisFileDirectory: W:\test\build\
> SET_VAR Configuration: Debug
> SET_VAR Platform: x64
> SET_VAR ProjectGuid: {C46EF444-71A0-37CE-9281-A9D8CA539B3E}
> SET_VAR Keyword: Win32Proj
> SET_VAR Platform: x64
> SET_VAR ProjectName: ALL_BUILD
> SET_VAR VCProjectUpgraderObjectName: NoUpgrade
> Could not find property sheet \Microsoft.Cpp.Default.props
> SET_VAR ConfigurationType: Utility
> SET_VAR CharacterSet: MultiByte
> SET_VAR PlatformToolset: v140
> Could not find property sheet \Microsoft.Cpp.props
> SET_VAR _ProjectFileVersion: 10.0.20506.1
> SET_VAR IntDir: x64\Debug\ALL_BUILD\
> Could not find property sheet \Microsoft.Cpp.targets
> Force includes: 
> PCH not enabled for this project!
> Preprocessor definitions:
>   -D_DEBUG_FUNCTIONAL_MACHINERY
> Platform toolset: v140
> Additional includes:
>   
> Visual Studio location: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional
> MSCVER: 14.12.25827
> WinSDK version: 8.1
> Include directories:
>   W:\test\build
>   C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.12.25827\include
>   C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.12.25827\atlmfc\include
>   C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt
>   C:\Program Files (x86)\Windows Kits\8.1\Include\um
>   C:\Program Files (x86)\Windows Kits\8.1\Include\shared
>   C:\Program Files (x86)\Windows Kits\8.1\Include\winrt
>   
> Processing 0 cpps
> Deleting project specific variables:
>   _NT_SYMBOL_PATH
>   _NT_SYMCACHE_PATH
>   ALLUSERSPROFILE
>   APPDATA
>   CommonProgramFiles
>   CommonProgramFiles(x86)
>   CommonProgramW6432
>   COMPUTERNAME
>   ComSpec
>   FP_NO_HOST_CHECK
>   HOMEDRIVE
>   HOMEPATH
>   INCLUDE
>   INTEL_LICENSE_FILE
>   LOCALAPPDATA
>   LOGONSERVER
>   MSMPI_BIN
>   NUMBER_OF_PROCESSORS
>   OneDrive
>   OS
>   Path
>   PATHEXT
>   PROCESSOR_ARCHITECTURE
>   PROCESSOR_IDENTIFIER
>   PROCESSOR_LEVEL
>   PROCESSOR_REVISION
>   ProgramData
>   ProgramFiles
>   ProgramFiles(x86)
>   ProgramW6432
>   PSModulePath
>   PUBLIC
>   SESSIONNAME
>   SystemDrive
>   SystemRoot
>   TEMP
>   TMP
>   USERDNSDOMAIN
>   USERDOMAIN
>   USERNAME
>   USERPROFILE
>   VBOX_MSI_INSTALL_PATH
>   VS110COMNTOOLS
>   VS120COMNTOOLS
>   VS140COMNTOOLS
>   VSSDK140Install
>   windir
>   MSBuildProjectFullPath
>   ProjectDir
>   MSBuildProjectExtension
>   MSBuildProjectFile
>   MSBuildProjectName
>   MSBuildProjectDirectory
>   MSBuildProgramFiles32
>   ProjectName
>   TargetName
>   VisualStudioVersion
>   MSBuildToolsVersion
>   SolutionDir
>   MSBuildThisFileFullPath
>   MSBuildThisFileExtension
>   MSBuildThisFile
>   MSBuildThisFileName
>   MSBuildThisFileDirectory
>   Configuration
>   Platform
>   ProjectGuid
>   Keyword
>   VCProjectUpgraderObjectName
>   ConfigurationType
>   CharacterSet
>   PlatformToolset
>   _ProjectFileVersion
>   IntDir
> 
> PROJECT #2: W:\test\build\ZERO_CHECK.vcxproj
> Importing environment variables into current scope
> SET_VAR _NT_SYMBOL_PATH: srv*P:\Symbols*http://msdl.microsoft.com/download/symbols
> SET_VAR _NT_SYMCACHE_PATH: P:\SymCache
> SET_VAR ALLUSERSPROFILE: C:\ProgramData
> SET_VAR APPDATA: C:\Users\reinbach\AppData\Roaming
> SET_VAR CommonProgramFiles: C:\Program Files\Common Files
> SET_VAR CommonProgramFiles(x86): C:\Program Files (x86)\Common Files
> SET_VAR CommonProgramW6432: C:\Program Files\Common Files
> SET_VAR COMPUTERNAME: VGPC45
> SET_VAR ComSpec: C:\Windows\system32\cmd.exe
> SET_VAR FP_NO_HOST_CHECK: NO
> SET_VAR HOMEDRIVE: C:
> SET_VAR HOMEPATH: \Users\reinbach
> SET_VAR INCLUDE: W:\test\build;C:\Program Files (x86)\Microsoft Visual 
> Studio\2017\Professional\VC\Tools\MSVC\14.12.25827\include;C:\Program Files (x86)\Microsoft Visual 
> Studio\2017\Professional\VC\Tools\MSVC\14.12.25827\atlmfc\include;C:\Program Files (x86)\Windows 
> Kits\10\Include\10.0.10240.0\ucrt;C:\Program Files (x86)\Windows Kits\8.1\Include\um;C:\Program Files (x86)\Windows 
> Kits\8.1\Include\shared;C:\Program Files (x86)\Windows Kits\8.1\Include\winrt;
> SET_VAR INTEL_LICENSE_FILE: C:\Program Files (x86)\Common Files\Intel\Licenses
> SET_VAR LOCALAPPDATA: C:\Users\reinbach\AppData\Local
> SET_VAR LOGONSERVER: \\DC2
> SET_VAR MSMPI_BIN: C:\Program Files\Microsoft MPI\Bin\
> SET_VAR NUMBER_OF_PROCESSORS: 24
> SET_VAR OneDrive: P:\reinbach\OneDrive
> SET_VAR OS: Windows_NT
> SET_VAR Path: %SystemRoot%\system32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft 
> MPI\Bin\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Windows Resource Kits\Tools\;C:\Windows\system32;C:
> \Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;c:\Program Files (x86)\Microsoft SQL 
> Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL 
> Server\100\DTS\Binn\;C:\Program Files\Microsoft Windows Performance Toolkit\;C:\Program Files (x86)\Windows 
> Kits\8.0\Windows Performance Toolkit\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files 
> (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files 
> (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program 
> Files (x86)\Visual Leak Detector\bin\Win32;C:\Program Files (x86)\Visual Leak Detector\bin\Win64;C:\Program 
> Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performance 
> Toolkit\;C:\Program Files\TortoiseGit\bin;C:\HashiCorp\Vagrant\bin;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windo
> ws\System32\WindowsPowerShell\v1.0\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\Git\cmd;C:\Program 
> Files\CMake\bin;C:\Users\reinbach\AppData\Local\Conan\conan;c:\work\bin;C:\Program Files\Microsoft 
> MPI\Bin\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Windows Resource Kits\Tools\;C:\Windows\system32;C:
> \Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;c:\Program Files (x86)\Microsoft SQL 
> Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL 
> Server\100\DTS\Binn\;C:\Program Files\Microsoft Windows Performance Toolkit\;C:\Program Files (x86)\Windows 
> Kits\8.0\Windows Performance Toolkit\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files 
> (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files 
> (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program 
> Files (x86)\Visual Leak Detector\bin\Win32;C:\Program Files (x86)\Visual Leak Detector\bin\Win64;C:\Program 
> Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performance 
> Toolkit\;C:\Program Files\TortoiseGit\bin;C:\HashiCorp\Vagrant\bin;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windo
> ws\System32\WindowsPowerShell\v1.0\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\Git\cmd;C:\Program 
> Files\CMake\bin;C:\Users\reinbach\AppData\Local\Gource\cmd;C:\Program Files\LLVM\bin
> SET_VAR PATHEXT: .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL
> SET_VAR PROCESSOR_ARCHITECTURE: AMD64
> SET_VAR PROCESSOR_IDENTIFIER: Intel64 Family 6 Model 44 Stepping 2, GenuineIntel
> SET_VAR PROCESSOR_LEVEL: 6
> SET_VAR PROCESSOR_REVISION: 2c02
> SET_VAR ProgramData: C:\ProgramData
> SET_VAR ProgramFiles: C:\Program Files
> SET_VAR ProgramFiles(x86): C:\Program Files (x86)
> SET_VAR ProgramW6432: C:\Program Files
> SET_VAR PSModulePath: C:\Users\reinbach\Documents\WindowsPowerShell\Modules;C:\Program 
> Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules
> SET_VAR PUBLIC: C:\Users\Public
> SET_VAR SESSIONNAME: Console
> SET_VAR SystemDrive: C:
> SET_VAR SystemRoot: C:\Windows
> SET_VAR TEMP: C:\Windows\TEMP
> SET_VAR TMP: C:\Users\reinbach\AppData\Local\Temp
> SET_VAR USERDNSDOMAIN: VOLUMEGRAPHICS.COM
> SET_VAR USERDOMAIN: VOLUMEGRAPHICS
> SET_VAR USERNAME: reinbach
> SET_VAR USERPROFILE: C:\Users\reinbach
> SET_VAR VBOX_MSI_INSTALL_PATH: C:\Program Files\Oracle\VirtualBox\
> SET_VAR VS110COMNTOOLS: C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\Tools\
> SET_VAR VS120COMNTOOLS: C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools\
> SET_VAR VS140COMNTOOLS: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\
> SET_VAR VSSDK140Install: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VSSDK\
> SET_VAR windir: C:\Windows
> SET_VAR MSBuildProjectFullPath: W:\test\build\ZERO_CHECK.vcxproj
> SET_VAR ProjectDir: W:\test\build\
> SET_VAR MSBuildProjectExtension: .vcxproj
> SET_VAR MSBuildProjectFile: ZERO_CHECK.vcxproj
> SET_VAR MSBuildProjectName: ZERO_CHECK
> SET_VAR MSBuildProjectDirectory: W:\test\build\
> SET_VAR MSBuildProgramFiles32: C:\Program Files (x86)
> SET_VAR ProjectName: ZERO_CHECK
> SET_VAR TargetName: ZERO_CHECK
> SET_VAR VisualStudioVersion: 15.0
> SET_VAR MSBuildToolsVersion: 15.0
> SET_VAR SolutionDir: W:\test\build\
> 
> Sanitizing W:\test\build\ZERO_CHECK.vcxproj
> SET_VAR MSBuildThisFileFullPath: W:\test\build\ZERO_CHECK.vcxproj
> SET_VAR MSBuildThisFileExtension: .vcxproj
> SET_VAR MSBuildThisFile: ZERO_CHECK.vcxproj
> SET_VAR MSBuildThisFileName: ZERO_CHECK
> SET_VAR MSBuildThisFileDirectory: W:\test\build\
> SET_VAR Configuration: Debug
> SET_VAR Platform: x64
> SET_VAR ProjectGuid: {0460C0D8-33F0-3E84-A3DE-7A3D875155BB}
> SET_VAR Keyword: Win32Proj
> SET_VAR Platform: x64
> SET_VAR ProjectName: ZERO_CHECK
> SET_VAR VCProjectUpgraderObjectName: NoUpgrade
> Could not find property sheet \Microsoft.Cpp.Default.props
> SET_VAR ConfigurationType: Utility
> SET_VAR CharacterSet: MultiByte
> SET_VAR PlatformToolset: v140
> Could not find property sheet \Microsoft.Cpp.props
> SET_VAR _ProjectFileVersion: 10.0.20506.1
> SET_VAR IntDir: x64\Debug\ZERO_CHECK\
> Could not find property sheet \Microsoft.Cpp.targets
> Force includes: 
> PCH not enabled for this project!
> Preprocessor definitions:
>   -D_DEBUG_FUNCTIONAL_MACHINERY
> Platform toolset: v140
> Additional includes:
>   
> Visual Studio location: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional
> MSCVER: 14.12.25827
> WinSDK version: 8.1
> Include directories:
>   W:\test\build
>   C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.12.25827\include
>   C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.12.25827\atlmfc\include
>   C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt
>   C:\Program Files (x86)\Windows Kits\8.1\Include\um
>   C:\Program Files (x86)\Windows Kits\8.1\Include\shared
>   C:\Program Files (x86)\Windows Kits\8.1\Include\winrt
>   
> Processing 0 cpps
> Deleting project specific variables:
>   _NT_SYMBOL_PATH
>   _NT_SYMCACHE_PATH
>   ALLUSERSPROFILE
>   APPDATA
>   CommonProgramFiles
>   CommonProgramFiles(x86)
>   CommonProgramW6432
>   COMPUTERNAME
>   ComSpec
>   FP_NO_HOST_CHECK
>   HOMEDRIVE
>   HOMEPATH
>   INCLUDE
>   INTEL_LICENSE_FILE
>   LOCALAPPDATA
>   LOGONSERVER
>   MSMPI_BIN
>   NUMBER_OF_PROCESSORS
>   OneDrive
>   OS
>   Path
>   PATHEXT
>   PROCESSOR_ARCHITECTURE
>   PROCESSOR_IDENTIFIER
>   PROCESSOR_LEVEL
>   PROCESSOR_REVISION
>   ProgramData
>   ProgramFiles
>   ProgramFiles(x86)
>   ProgramW6432
>   PSModulePath
>   PUBLIC
>   SESSIONNAME
>   SystemDrive
>   SystemRoot
>   TEMP
>   TMP
>   USERDNSDOMAIN
>   USERDOMAIN
>   USERNAME
>   USERPROFILE
>   VBOX_MSI_INSTALL_PATH
>   VS110COMNTOOLS
>   VS120COMNTOOLS
>   VS140COMNTOOLS
>   VSSDK140Install
>   windir
>   MSBuildProjectFullPath
>   ProjectDir
>   MSBuildProjectExtension
>   MSBuildProjectFile
>   MSBuildProjectName
>   MSBuildProjectDirectory
>   MSBuildProgramFiles32
>   ProjectName
>   TargetName
>   VisualStudioVersion
>   MSBuildToolsVersion
>   SolutionDir
>   MSBuildThisFileFullPath
>   MSBuildThisFileExtension
>   MSBuildThisFile
>   MSBuildThisFileName
>   MSBuildThisFileDirectory
>   Configuration
>   Platform
>   ProjectGuid
>   Keyword
>   VCProjectUpgraderObjectName
>   ConfigurationType
>   CharacterSet
>   PlatformToolset
>   _ProjectFileVersion
>   IntDir
> 
> PROJECT: W:\test\build\example.vcxproj
> Importing environment variables into current scope
> SET_VAR _NT_SYMBOL_PATH: srv*P:\Symbols*http://msdl.microsoft.com/download/symbols
> SET_VAR _NT_SYMCACHE_PATH: P:\SymCache
> SET_VAR ALLUSERSPROFILE: C:\ProgramData
> SET_VAR APPDATA: C:\Users\reinbach\AppData\Roaming
> SET_VAR CommonProgramFiles: C:\Program Files\Common Files
> SET_VAR CommonProgramFiles(x86): C:\Program Files (x86)\Common Files
> SET_VAR CommonProgramW6432: C:\Program Files\Common Files
> SET_VAR COMPUTERNAME: VGPC45
> SET_VAR ComSpec: C:\Windows\system32\cmd.exe
> SET_VAR FP_NO_HOST_CHECK: NO
> SET_VAR HOMEDRIVE: C:
> SET_VAR HOMEPATH: \Users\reinbach
> SET_VAR INCLUDE: W:\test\build;C:\Program Files (x86)\Microsoft Visual 
> Studio\2017\Professional\VC\Tools\MSVC\14.12.25827\include;C:\Program Files (x86)\Microsoft Visual 
> Studio\2017\Professional\VC\Tools\MSVC\14.12.25827\atlmfc\include;C:\Program Files (x86)\Windows 
> Kits\10\Include\10.0.10240.0\ucrt;C:\Program Files (x86)\Windows Kits\8.1\Include\um;C:\Program Files (x86)\Windows 
> Kits\8.1\Include\shared;C:\Program Files (x86)\Windows Kits\8.1\Include\winrt;
> SET_VAR INTEL_LICENSE_FILE: C:\Program Files (x86)\Common Files\Intel\Licenses
> SET_VAR LOCALAPPDATA: C:\Users\reinbach\AppData\Local
> SET_VAR LOGONSERVER: \\DC2
> SET_VAR MSMPI_BIN: C:\Program Files\Microsoft MPI\Bin\
> SET_VAR NUMBER_OF_PROCESSORS: 24
> SET_VAR OneDrive: P:\reinbach\OneDrive
> SET_VAR OS: Windows_NT
> SET_VAR Path: %SystemRoot%\system32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft 
> MPI\Bin\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Windows Resource Kits\Tools\;C:\Windows\system32;C:
> \Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;c:\Program Files (x86)\Microsoft SQL 
> Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL 
> Server\100\DTS\Binn\;C:\Program Files\Microsoft Windows Performance Toolkit\;C:\Program Files (x86)\Windows 
> Kits\8.0\Windows Performance Toolkit\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files 
> (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files 
> (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program 
> Files (x86)\Visual Leak Detector\bin\Win32;C:\Program Files (x86)\Visual Leak Detector\bin\Win64;C:\Program 
> Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performance 
> Toolkit\;C:\Program Files\TortoiseGit\bin;C:\HashiCorp\Vagrant\bin;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windo
> ws\System32\WindowsPowerShell\v1.0\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\Git\cmd;C:\Program 
> Files\CMake\bin;C:\Users\reinbach\AppData\Local\Conan\conan;c:\work\bin;C:\Program Files\Microsoft 
> MPI\Bin\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Windows Resource Kits\Tools\;C:\Windows\system32;C:
> \Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;c:\Program Files (x86)\Microsoft SQL 
> Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL 
> Server\100\DTS\Binn\;C:\Program Files\Microsoft Windows Performance Toolkit\;C:\Program Files (x86)\Windows 
> Kits\8.0\Windows Performance Toolkit\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files 
> (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files 
> (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program 
> Files (x86)\Visual Leak Detector\bin\Win32;C:\Program Files (x86)\Visual Leak Detector\bin\Win64;C:\Program 
> Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performance 
> Toolkit\;C:\Program Files\TortoiseGit\bin;C:\HashiCorp\Vagrant\bin;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windo
> ws\System32\WindowsPowerShell\v1.0\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\Git\cmd;C:\Program 
> Files\CMake\bin;C:\Users\reinbach\AppData\Local\Gource\cmd;C:\Program Files\LLVM\bin
> SET_VAR PATHEXT: .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL
> SET_VAR PROCESSOR_ARCHITECTURE: AMD64
> SET_VAR PROCESSOR_IDENTIFIER: Intel64 Family 6 Model 44 Stepping 2, GenuineIntel
> SET_VAR PROCESSOR_LEVEL: 6
> SET_VAR PROCESSOR_REVISION: 2c02
> SET_VAR ProgramData: C:\ProgramData
> SET_VAR ProgramFiles: C:\Program Files
> SET_VAR ProgramFiles(x86): C:\Program Files (x86)
> SET_VAR ProgramW6432: C:\Program Files
> SET_VAR PSModulePath: C:\Users\reinbach\Documents\WindowsPowerShell\Modules;C:\Program 
> Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules
> SET_VAR PUBLIC: C:\Users\Public
> SET_VAR SESSIONNAME: Console
> SET_VAR SystemDrive: C:
> SET_VAR SystemRoot: C:\Windows
> SET_VAR TEMP: C:\Windows\TEMP
> SET_VAR TMP: C:\Users\reinbach\AppData\Local\Temp
> SET_VAR USERDNSDOMAIN: VOLUMEGRAPHICS.COM
> SET_VAR USERDOMAIN: VOLUMEGRAPHICS
> SET_VAR USERNAME: reinbach
> SET_VAR USERPROFILE: C:\Users\reinbach
> SET_VAR VBOX_MSI_INSTALL_PATH: C:\Program Files\Oracle\VirtualBox\
> SET_VAR VS110COMNTOOLS: C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\Tools\
> SET_VAR VS120COMNTOOLS: C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools\
> SET_VAR VS140COMNTOOLS: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\
> SET_VAR VSSDK140Install: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VSSDK\
> SET_VAR windir: C:\Windows
> SET_VAR MSBuildProjectFullPath: W:\test\build\example.vcxproj
> SET_VAR ProjectDir: W:\test\build\
> SET_VAR MSBuildProjectExtension: .vcxproj
> SET_VAR MSBuildProjectFile: example.vcxproj
> SET_VAR MSBuildProjectName: example
> SET_VAR MSBuildProjectDirectory: W:\test\build\
> SET_VAR MSBuildProgramFiles32: C:\Program Files (x86)
> SET_VAR ProjectName: example
> SET_VAR TargetName: example
> SET_VAR VisualStudioVersion: 15.0
> SET_VAR MSBuildToolsVersion: 15.0
> SET_VAR SolutionDir: W:\test\build\
> 
> Sanitizing W:\test\build\example.vcxproj
> SET_VAR MSBuildThisFileFullPath: W:\test\build\example.vcxproj
> SET_VAR MSBuildThisFileExtension: .vcxproj
> SET_VAR MSBuildThisFile: example.vcxproj
> SET_VAR MSBuildThisFileName: example
> SET_VAR MSBuildThisFileDirectory: W:\test\build\
> SET_VAR Configuration: Debug
> SET_VAR Platform: x64
> SET_VAR ProjectGuid: {BFC7744C-6582-37FC-B5DF-AEF664DA5D34}
> SET_VAR Keyword: Win32Proj
> SET_VAR Platform: x64
> SET_VAR ProjectName: example
> SET_VAR VCProjectUpgraderObjectName: NoUpgrade
> Could not find property sheet \Microsoft.Cpp.Default.props
> SET_VAR ConfigurationType: Application
> SET_VAR CharacterSet: MultiByte
> SET_VAR PlatformToolset: v140
> Could not find property sheet \Microsoft.Cpp.props
> SET_VAR _ProjectFileVersion: 10.0.20506.1
> SET_VAR OutDir: W:\test\build\Debug\
> SET_VAR IntDir: example.dir\Debug\
> SET_VAR TargetName: example
> SET_VAR TargetExt: .exe
> SET_VAR LinkIncremental: true
> SET_VAR GenerateManifest: true
> Could not find property sheet \Microsoft.Cpp.targets
> Force includes: 
> PCH not enabled for this project!
> Preprocessor definitions:
>   -DWIN32
>   -D_WINDOWS
>   -DPROJECT_NAME="""example"""
>   -DSTRING_WITH_SPACE="""STRING WITH SPACE"""
>   -DCMAKE_INTDIR="""Debug"""
>   -D_DEBUG_FUNCTIONAL_MACHINERY
> Platform toolset: v140
> Additional includes:
>   
> Visual Studio location: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional
> MSCVER: 14.12.25827
> WinSDK version: 8.1
> Include directories:
>   W:\test\build
>   C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.12.25827\include
>   C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.12.25827\atlmfc\include
>   C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt
>   C:\Program Files (x86)\Windows Kits\8.1\Include\um
>   C:\Program Files (x86)\Windows Kits\8.1\Include\shared
>   C:\Program Files (x86)\Windows Kits\8.1\Include\winrt
>   
> Processing 1 cpps
> Clang job tool: clang++.exe
> Clang job args[0]: -x c++ "W:\test\build\main.cpp" -std=c++14 -Werror -Wall -fms-compatibility-version=19.10 
> -Wmicrosoft -Wno-invalid-token-paste -Wno-unknown-pragmas -Wno-unused-value -fsyntax-only -DWIN32 -D_WINDOWS 
> -DPROJECT_NAME="""example""" -DSTRING_WITH_SPACE="""STRING WITH SPACE""" -DCMAKE_INTDIR="""Debug""" 
> -D_DEBUG_FUNCTIONAL_MACHINERY
> 1: W:\test\build\main.cpp
> clang++.exe: error: no such file or directory: 'WITH'
> clang++.exe: error: no such file or directory: 'SPACE"'
> 
> 
> Got errors.
> Cleaning up PCH temporaries:
>

**Comment by hero101111** [comment]
Hello,

Unfortunately we missed a typo regarding the double quote escaping.
We've just pushed a fix for it.

Sorry for the inconvenience.

Regards,
Gabriel


---

Please note that this fix is currently live only for the github repository.
The latest Visual Studio extension does not contain the fix. It will be included in the next release.

Until then, as a workaround, you can manually replace `clang-build.ps1` in the VS extension directory with the latest from github. To locate the extension directory search for `clang-build.ps1` in `%LOCALAPPDATA%`

Don't forget to restart Visual Studio after replacing the script file.

**Comment by eel76** [comment]
@hero101111  I tried it again, today. Unfortunately it doesn't work yet:

> VERBOSE: Clang job args[0]: -x c++ "W:\example\build\main.cpp" -std=c++14 -Werror -Wall
> -fms-compatibility-version=19.10 -Wmicrosoft -Wno-invalid-token-paste -Wno-unknown-pragmas -Wno-unused-value
> -fsyntax-only -DWIN32 -D_WINDOWS -DPROJECT_NAME=""example"" -DSTRING_WITH_SPACE=""STRING WITH SPACE""
> -DCMAKE_INTDIR=""Debug"" -D_DEBUG_FUNCTIONAL_MACHINERY
> 1: W:\example\build\main.cpp
> clang++.exe: error: no such file or directory: 'WITH'
> clang++.exe: error: no such file or directory: 'SPACE'
> 
> 
> Got errors.

**Comment by hero101111** [comment]
Hi again,

We apologize for the nonworking fix. It fooled us into thinking it was ok because we tested it with only one double quote character, not two or more.

We pushed a new fix that should finally fix your problem.
Please re-test and let us know if everything is working.

Best regards,
Gabriel


---

Please note that this fix is currently live only for the github repository.
The latest Visual Studio extension (`2.5.1`) does not contain the fix. It will be included in the next release.

Until then, as a workaround, you can manually replace `clang-build.ps1` in the VS extension directory with the latest from github. To locate the extension directory search for `clang-build.ps1` in `%LOCALAPPDATA%`

Don't forget to restart Visual Studio after replacing the script file.

**Comment by eel76** [comment]
Yeah great. Now everything works as expected :+1:
