### ISSUE TITLE
Environment variables in vcxproj not replaced

### ISSUE THREAD

**Issue by zebmason** [Caphyon/clang-power-tools#33]
Example output doesn't replace $(GeoSLAM) with C:\Repositories\ct-geoslam and thus prepends the current directory. i.e. Path should be 
C:\Repositories\ct-geoslam\src\nrrslam\apps\dataset_merger\src\apply_transform.cpp
and not
C:\Repositories\win-geoslam\geoslam\$(GeoSLAM)\src\nrrslam\apps\dataset_merger\src\apply_transform.cpp

Unfortunately I've never done any PowerShell so cannot fix myself.

===

Start Clang Compile

[ INFO ] WILL PROCESS PROJECTS: 
	apply_transform.vcxproj
[ INFO ] 1. PROCESSING PROJECT C:\Repositories\win-geoslam\geoslam\apply_transform.vcxproj
Join-Path : Cannot find path 
'C:\Repositories\win-geoslam\geoslam\$(GeoSLAM)\src\nrrslam\apps\dataset_merger\src\apply_transform.cpp' because it 
does not exist.
At C:\Users\Zeb\AppData\Local\Microsoft\VisualStudio\15.0_8121d886\Extensions\lryuk1gn.tm5\clang-build.ps1:297 char:22
+ ... ng] $path = Join-Path -Path "$base" -ChildPath "$child" -Resolve -Err ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Repositories...y_transform.cpp:String) [Join-Path], ItemNotFoundExce 
   ption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.JoinPathCommand
 

Done Clang Compile

**Comment by cpp-red-lion** [comment]
Currently we don't have support for MSBuild properties or environment variables.
This is something we could add in a future version.
Thanks for your feedback.

**Comment by hero101111** [comment]
Hi,

We're happy to inform you that we've just released version 2.0 of [Clang Power Tools](https://marketplace.visualstudio.com/items?itemName=vs-publisher-690586.ClangPowerTools).
It fixes the project xml data [limitations](https://github.com/Caphyon/clang-power-tools/blob/master/CHANGELOG.md) that were at the core of this issue.

Projects with user-defined macros (properties) should now integrate successfully with Clang Power Tools.

The Visual Studio Extension should now update automatically to v2.0. 
If you've disabled automatic updates you'll have to update the extension manually.


Thank you for feedback and patience.

Regards,
Gabriel.

**Comment by neusdan** [comment]
First of all, thanks for your great work.

Unfortunately, for me, environment variables in include paths are still not working. There is no error, the path from the environment variable is just missing.

**Comment by neusdan** [comment]
I am using version 2.0. 

Even tried to achieve it with user-defined macros, but they are also not evaluated.
