### ISSUE TITLE
Add support for MSBuild::MakeRelative property function

### ISSUE THREAD

**Issue by adamf88** [Caphyon/clang-power-tools#369]
If I create .props file as below (file.props):

```
<?xml version="1.0" encoding="utf-8"?> 
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
	  <DepsPath>$([MSBuild]::MakeRelative($(ProjectDir),$(MSBuildThisFileFullPath)\..))</DepsPath>
	  <AAAIncludeDir>$(DepsPath)test_lib\include</AAAIncludeDir>
  </PropertyGroup>
  <ItemDefinitionGroup />
  <ItemGroup />
</Project>
```

And then in my cpp projects I can add this property sheet and specify Additional Include Directories as:
`<AdditionalIncludeDirectories>$(AAAIncludeDir);%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>`

Unfortunately clang power tools can't find header files from 'test_lib\include' directory. I receive error like:

C:\Users\Test\Desktop\ClangPowerTools\main.cpp:1:10: fatal error: 'test.h' file not found
#include "test.h"
         ^~~~~~~~
1 error generated.
Got errors.
Done Clang Compile

More details about Property Functions:
https://docs.microsoft.com/en-us/visualstudio/msbuild/property-functions

**Comment by hero101111** [comment]
Hello @adamf88 ,

ClangPowerTools already has support for most property functions, albeit not the one you're using.
We've pushed a code update for `[MSBuild]::MakeRelative`. and will release an updated CPT version soon.

Thanks for your feedback.

Regards,
Gabriel

**Comment by adamf88** [comment]
Thanks for the fast update.
Unfortunately I still can't run my case. I have added minimal project to reproduce the problem in attachment.

deps\deps.props -> property sheet with my MakeRelative function
Application\Console.sln -> sample application (it uses deps.prop). I can compile it with Visual Studio, but running "Compile (syntax only)" generates an error:

#include "test.h"
         ^~~~~~~~
1 error generated.
Got errors.

[PropsTest.zip](https://github.com/Caphyon/clang-power-tools/files/2161028/PropsTest.zip)

**Comment by hero101111** [comment]
Hi again,

Thanks for the sample project, we've been able to figure out the problem.
Turns out we've missed a corner case regarding trailing slashes, your include path ended up missing a slash separator.

Stand by for a fix, it'll come with `v3.7.1`, to be released today.
