### ISSUE TITLE
Access rights powershell script

### ISSUE THREAD

**Issue by jcageman** [Caphyon/clang-power-tools#493]
When using the compile option for Clang PowerTools i get the below error in my visual studio output window. 

```
. : File D:\me\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1 cannot be loaded because running script
s is disabled on this system. For more information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?Lin
kID=135170.
At line:1 char:3
+ . 'D:\me\Documents\WindowsPowerShell\Microsoft.PowerShell_profile ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
```

When looking at [ScriptConstants.cs](https://github.com/Caphyon/clang-power-tools/blob/1500c7af1e94a5068a2a034d7dc61449c97486ab/ClangPowerTools/ClangPowerTools/Script/ScriptConstants.cs) you call powershell with the following syntax:
`@"PowerShell.exe -ExecutionPolicy Bypass -NoProfile -Noninteractive -command '&";`

The given error suggests that Bypass is actually not activated and that my profile is still loaded?

PowerShellWrapper is using kPowerShellPath and in that case the above parameters are not supplied. Hence, i think PowerShellWrapper should alsoapply the above arguments?

Note: even though i get these errors the compilation continues, hence its not a showstopper.

I am on windows 10, VS2017 with version 4.5.0 of your plugin and visual studio started as administrator.

**Comment by Enache-Ionut** [comment]
Hi,

This issue was fixed and it will be available in the next Clang Power Tools version (4.6)

**Comment by ChrisGuzak** [comment]
Trying this tool out for the first time I see that this issue seems to still exist in 4.6.0. I see output after "Start Clang Tidy" that shows my profile script is being run

Start Clang Tidy

Set-PSReadLineOption : The term 'Set-PSReadLineOption' is not recognized as the name of a cmdlet, function, script 
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct 
and try again.
At C:\Users\Chris\OneDrive\PowerShellScripts\profile.ps1:5 char:1

**Comment by jcageman** [comment]
This is indeed not fixing it, please have a look at the hint i gave where the issue is located.

See: ClangPowerTools/Script/PowerShellWrapper.cs

**Comment by Enache-Ionut** [comment]
Hi,

Everything you said in your hint is already mentioned in the Arguments section of the Process.StartInfo. Currently we are searching for another way to run the powershell script. ChrisGuzak has created another issue for this #506 where he mentioned a possible problem. We will investigate it and a fix will be ready soon.

**Comment by Enache-Ionut** [comment]
How this is a duplicate issue I will close it now. You can follow the evolution of it here: https://github.com/Caphyon/clang-power-tools/issues/506. 

Thank you for taking the time and helping us make a better product.
