### ISSUE TITLE
Wrong evaluation of conditional properties

### ISSUE THREAD

**Issue by mkaes** [Caphyon/clang-power-tools#507]
I stumbled across a problem in a fairly complex project with conditional properties.
Unfortunalty I do not have a simplified project to reproduce this issue but when I find some time I will try to set one up.

The issue boils down to a property sheet defining a property like this
```xml
<Choose>  
  <When Condition=some_cond>
    <PropertyGroup>
      <P1>Foo</P1>
    </PropertyGroup>
  </When>
  <Otherwise>
    <PropertyGroup>
      <P1>Bar</P1>
    </PropertyGroup>
  </Otherwise>
</Choose>
```

If the condition is true everything works fine but when the condition is evaluated to false it seems that in `SanitizeProjectNode` the `when` node is scheduled for deletion but before this is done the `Otherwise` node is evaluated and discarded because the `when` node is still present.
The attached diff fixes the issue for me but I wonder if this might break other thing I did not find yet.
[delay_node_process_diff.txt](https://github.com/Caphyon/clang-power-tools/files/2787968/delay_node_process_diff.txt)

**Comment by hero101111** [comment]
We have reproduced the issue and a fix will be available in the next release of Clang Power Tools.
Thank you for your feedback.

**Comment by hero101111** [comment]
Please note that the latest release `4.7` did not fix this bug. Unfortunately, during unit tests, we discovered a regression caused by the fix and we are investigating this issue further. 

We'll update this thread as progress is made.
Thank you for your understanding.

**Comment by mkaes** [comment]
With the `4.8` release I can no longer reproduce this issue on my project. So I am closing this issue as fixed.

**Comment by mkaes** [comment]
I am sorry I was a little too fast on this one and messed up my patched version which the real `4.8`.
So I reopen this, as the issue still occurs in the `4.8` release.
Sorry.

**Comment by hero101111** [comment]
We have just pushed a fix for this bug, which will be included in the `4.9` release.

Thank you for the helping hand in fixing this issue,
Gabriel

**Comment by mkaes** [comment]
It still does not work with the 4.10 version without my patch.
So I guess there is still something wrong.
I was not yet able to strip our build system to an easily debuggable example.
But as soon as I understand msbuild good enough to do so, I will reopen this bug.

**Comment by mkaes** [comment]
I finally was able to make an example project.
It is possible to build the x86 and x64 config with visual studio but the clang tools always take the wrong condition. In this case a non valid path and thus a compile error.
I hope this helps.
[PropsTest.zip](https://github.com/Caphyon/clang-power-tools/files/3008387/PropsTest.zip)

**Comment by hero101111** [comment]
Thank you for taking the time to provide a sample project.
We'll use it to further look into this and update the thread as soon as we make progress.


-Gabriel.

**Comment by hero101111** [comment]
Hello again,

We've fixed this issue, pending release with `v4.10.3`.
Thank you for helping us investigate the issue.

Regards,
Gabriel.

**Comment by hero101111** [comment]
Can you please confirm that the issue is resolved on your end? (using CPT 4.10.3).

Thanks.

**Comment by mkaes** [comment]
I am sorry but it seems that the issue persists.
I am using 4.10.3 from 23.04
but compiling the test project I attached, there is still an error on my machine.

The verbose output shows that some conditionals are still wrong.
In case of the test project I can see that the include path is set to 
...PropsTest\v140-\include\my-1_0\;
but msvc evaluates it to 
...PropsTest\v140-x64\include\my-1_0\;
In the test project this is the MyPlatform conditional defined in prerequisite.props.

**Comment by mkaes** [comment]
It seems that this is quite a problem.
I will just go back to my initial change of the plugin.
It is a little cumbersome to patch the plugin after each update but it works in my case.

**Comment by hero101111** [comment]
Hello again,

We apologize for the continued inconvenience caused by this issue. 
A ClangPowerTools update will soon be released which will fix it.

Regards,
Gabriel.

**Comment by hero101111** [comment]
Retested the issue using the latest CPT (v7.2.0) and the attached sample project. Could not reproduce issue, the behavior is as expected, working on both Win32 and x64 conditional branches.

Closing this Github issue as a consequence of the problem not being reproducible.
