### ISSUE TITLE
File locked when saving using version 5.6.0

### ISSUE THREAD

**Issue by rtoumazet** [Caphyon/clang-power-tools#759]
Hi,
The plugin just got updated to version 5.6.0 on my Visual Studio 2019 instance, and I'm facing a curious problem : whenever I do a change to a file and try to save it, the "save as" dialog box appears. If I try to save the file anyway I get the following message :
![image](https://user-images.githubusercontent.com/34705093/76001674-bdae1880-5f05-11ea-9673-0f09f7916059.png)

After a while the lock seems to be removed and the file can be saved, but if I do another change it starts over again ...

Everything was fine using the previous version, I was wondering if it was available somewhere in order to check if the new version is at fault...
**Clang format** is disabled on Visual Studio, and **Format on save** is enabled in the plugin. I tried various combinations to no avail.
What I also tried :
- Starting Visual Studio as administrator
- Repairing Visual Studio and reinstalling the plugin

The outcome is the same everytime :(

Nevertheless, I love this plugin (when it works :D )

**Comment by ShadowIce** [comment]
Same here. I don't use Format on Save or anything else that should automatically trigger clang. But after the update I noticed that I suddenly had squiggles from clang-tidy in the editor window without ever running it manually. So my guess is that it now runs while saving, or after changing something in the file but there doesn't seem to be an option to disable it.

**Comment by hprica** [comment]
Hello @rtoumazet  and @ShadowIce,

Thank you for taking the time to report the bug. We have resolved your issue in the point release (5.6.1) we just published.

If you have any other problems or feature suggestions let us know.

Have a great weekend!

**Comment by rtoumazet** [comment]
Hello @hprica ,

I just installed version 5.6.1, and the problem is still present :/

**Comment by hprica** [comment]
Hello @rtoumazet,

Glad to hear that the main issue has been fixed 😄 

We are getting the "save as" window even without the extension installed. It started to appear more often a few Visual Studio versions prior if you save very often and the previous save action has not been completed. It is more likely to appear on very large files. 

Unfortunately, we have no control over the "save as" window from Visual Studio.

If you find any other issues or have feature suggestions let us know.

**Comment by rtoumazet** [comment]
Thanks for the explanation @hprica, and keep up the good work ;)
